Feat: 버튼 컴포넌트 구현
codeit-fe2-2/taskify pull request #21
Opened 2024-01-25 06:52 UTC by BBoBBoM

추상화 재사용을 위하여 특정 children일때 css처리로 구현 했습니다
살펴보고 다른 의견 있으시면 알려주세요
가능 children 로그인, 수락, 거절, 삭제, 대시보드 삭제하기 입니다

## 어떤 변경인지

- [x] Feat: 기능 변경, 기능 추가
- [ ] Docs: 문서 작업
- [ ] Refactor: 기능 변경 없이 코드 수정
- [ ] Style: 디자인
- [ ] Fix: 버그 수정
- [ ] Test: 테스트 코드 작성

## 설명

### 이슈 번호

> [https://github.com/codeit-fe2-2/taskify/issues/8#issue-2099383183]

### 주요 변경 사항
- 공통 컴포넌트 ui구현
- css 부분 children 으로 넘어오는 값을 비교하여 css적용 되도록 구현 
### 어떻게 동작하는지
<GeneralButton onClick={handleLoginClick}>로그인,수락,거절,삭제</GeneralButton> 와 같은 문자 입력시 해당 문자에 관한 button 기본형식으로 구성되어짐 각각 반응형 까지 구현하였음
![스크린샷 2024-01-25 155036](https://github.com/codeit-fe2-2/taskify/assets/131963909/53ffe993-c17d-443e-b9ed-ccc6c5189d32)
### To Reviewers

2024-01-25 06:58 UTC, 00TaciTa00 approved these changes
문제 없는 거 확인했습니다~

2024-01-25 07:28 UTC, ckswnskfk requested changes
엄청 빠른 구현 대단하십니다 👍
문자열로 받는 children에 따라 스타일을 조정하는 건 그 외의 문자열이 들어왔을 때 대비하기가 어렵고 확장성이 낮은 방법인 것 같습니다. 대신 type 등을 props로 받아서 확장성을 넓히는 방법은 어떨까요?
ex)
```
interface GeneralButtonProps {
	children: ReactNode;
        type: 'outlined' | 'primary' ...
	onClick: (event: event) => void;
	...
}
```
제 생각엔 배경색에 따라 몇 가지만 다르면 될 것 같은데 어떻게 생각하시나요?
더불어 페이지 이동의 요소도 있으니 next의 Link 컴포넌트로 동작하는 방법도 있으면 좋을 것 같아요!

2024-01-25 07:28 UTC, ckswnskfk commented on src/components/ui/GeneralButton.tsx
> +	children: string;
버튼으로 들어오는 글자에 따라 스타일을 다르게 하신 것 같은데 아이콘 등 다른 요소가 children으로 들어오는 경우는 어떻게 처리하나요? 👀

2024-01-25 07:28 UTC, ckswnskfk commented on src/components/ui/GeneralButton.tsx
> +	isDisabled = false,
개인적으론 isDisabled 대신 피그마처럼 inactive가 더 적절한 네이밍 같습니다!

2024-01-25 07:28 UTC, ckswnskfk commented on tailwind.config.ts
> +			lg: { min: '1200px' },
ㅋㅋㅋㅋㅋ감사합니다!

2024-01-25 14:43 UTC, 00TaciTa00 approved these changes

2024-01-26 00:50 UTC, ckswnskfk reviewed
고생하셨습니다! 확장성 부분에서 좀 욕심 나는 부분이 있는데 어느정도 까지 반영하는 게 좋을지는 이따 팀 회의 때 같이 얘기해보면 어떨까요?

2024-01-26 00:50 UTC, ckswnskfk commented on src/components/ui/GeneralButton.tsx
> +import arrowNext from '../../../public/icons/arrowNext.svg';
아직 논의가 안되긴 했는데 import 시 절대경로로 통일하면 어떨까요?
관련 세팅은 찾아보고는 있는데 다 같이 찾아보면 좋을 것 같아요!

2024-01-26 00:50 UTC, ckswnskfk commented on src/components/ui/GeneralButton.tsx
> +	| 'next';
제 생각엔 대표적인 디자인에 따라 타입을 나누는 게 더 사용하기 쉬울 것 같아요. 지금 같은 타입 분류는 매번 시안에 들어가서 어떤 디자인인지 확인하거나 버튼 컴포넌트의 타입을 다 외워야 사용할 수 있을 것 같습니다!

2024-01-26 00:50 UTC, ckswnskfk commented on src/components/ui/GeneralButton.tsx
> +			)}
buttonText가 없으면 아이콘이 있는 Link로 기능하는 조건이죠? 시안을 보면 화살표 아이콘은 페이지네이션에서 주로 사용되는 것 같은데 링크 이동 없이 동작할 것 같아요.
그리고 다른 아이콘을 버튼으로 사용하고 싶을 땐 어떻게 사용하면 좋을까요? 👀

2024-01-26 00:51 UTC, ckswnskfk approved these changes

2024-01-26 01:10 UTC, caseV12 approved these changes
확인했습니다~ 재환님 코드랑 찬주님 리뷰 도움 많이 되었습니다 감사합니다!

2024-01-27 02:46 UTC, closed without merging