Feature/case v12/2
codeit-fe2-2/taskify pull request #24
Opened 2024-01-26 06:33 UTC by caseV12

## 어떤 변경인지

- [ ] Feat: 기능 변경, 기능 추가
- [ ] Docs: 문서 작업
- [ ] Refactor: 기능 변경 없이 코드 수정
- [ ] Style: 디자인
- [ ] Fix: 버그 수정
- [ ] Test: 테스트 코드 작성

## 설명

### 이슈 번호

> 예) .../codeit-fe2-2/taskify/issues/**7**
> https://github.com/codeit-fe2-2/taskify/issues/

### 주요 변경 사항

### 어떻게 동작하는지

### To Reviewers

2024-01-26 12:20 UTC, 00TaciTa00 requested changes

2024-01-26 12:20 UTC, 00TaciTa00 commented on src/components/ui/Input.tsx
> +	},
<img width="286" alt="image" src="https://github.com/codeit-fe2-2/taskify/assets/79896328/662a93c6-536b-4bc5-8d8d-4f3bc6a4b684">
이렇게 이메일 형식으로 넣었는데도 에러메세지가 떠서... 한 번 확인해보시는게 어떨까요?

2024-01-26 12:20 UTC, 00TaciTa00 commented on pages/test/index.tsx
> +			<Input type='password-check' password='12345678a' />
이거 password는 나중에 페이지에서 값을 받을 수 있도록 해둔 거죠? 그럼 문제 없습니다~

2024-01-27 04:50 UTC, caseV12 commented on src/components/ui/Input.tsx
> +	},
넵  수정하면서 확인해보겠습니다 감사합니다

2024-01-27 04:50 UTC, caseV12 commented on pages/test/index.tsx
> +			<Input type='password-check' password='12345678a' />
넵 form에서 쓸 때 password꺼 리프팅한 다음에 다시 내리게 하는 쪽으로 생각했습니다

2024-01-27 12:44 UTC, caseV12 commented on src/components/ui/Input.tsx
> +	type: GeneralInputType;
GeneralInputProps에
type: Exclude<HTMLInputTypeAttribute, 'email' | 'password'>;
로 password와 email일 경우 regex와 invalidMessage 강제하고 싶었으나 HTMLInputTypeAttribute에  (string & {})이 포함되어 있어서 Exclude 사용 시에도 'email'과 'password'를 포함한 모든 문자열이 GenearlInputProps로 추론되는 문제가 있었습니다. 그래서 그냥 문자열 리터럴 사용하였습니다.

2024-01-27 12:49 UTC, caseV12 commented on src/components/ui/Input.tsx
> +		: event.target.removeAttribute('data-invalid');
validity를 state로 빼는 것도 고려했으나 기존 HTML 속성과 tailwind의 peer 속성 활용을 위해 직접 DOM을 조작하는 쪽으로 했습니다.

2024-01-27 13:32 UTC, caseV12 commented on pages/test/index.tsx
> +			<Input type='password-check' password='12345678a' />
비밀번호 확인만 추가적인 인자를 필요로 하는 것은 이상한 로직인 거 같아서 전체 바꾸면서 위에서 password꺼 끌어올린 다음에 regex로 보내도록 했습니다.

2024-01-28 05:05 UTC, ckswnskfk approved these changes
추상화에 대해 고민을 많이 하신 게 느껴지네요..! 👍
약간 어려워서 사용하려면 컴포넌트 내부 동작을 분석해야 해야 하는 부분이 있는 것 같긴 하지만 이미 훌륭하게 작성하신 것 같습니다!

2024-01-28 05:05 UTC, ckswnskfk commented on src/components/ui/Input.tsx
> +		onChange,
제가 봤을 땐 [controlled](https://dori-coding.tistory.com/entry/React-%EC%A0%9C%EC%96%B4-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8Controlled-Component%EC%99%80-%EB%B9%84%EC%A0%9C%EC%96%B4-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8Uncontrolled-Component) 되지 않아도 동작이 잘 될 것 같아요. 매 입력마다 불필요한 리렌더링이 일어날 수도 있을 것 같아요.

2024-01-28 05:05 UTC, ckswnskfk commented on src/components/ui/Input.tsx
> +					pattern={regex}
와 이런 속성이 있는 것도 처음 알았습니다ㅋㅋㅋ 👍

2024-01-28 06:19 UTC, caseV12 commented on src/components/ui/Input.tsx
> +					pattern={regex}
꼼꼼한 리뷰 감사합니다!! 제어/비제어, ID 고유성 보장 안되어 있는 문제 등등 많이 배웠습니다👍👍👍

2024-01-29 11:35 UTC, merged