Feat: Chips와 ModalButton 컴포넌트 작성 미완성 (#10, #12)
codeit-fe2-2/taskify pull request #29
Opened 2024-01-27 12:04 UTC by Nebaisgood

## 어떤 변경인지

- [x] Feat: 기능 변경, 기능 추가
- [ ] Docs: 문서 작업
- [ ] Refactor: 기능 변경 없이 코드 수정
- [ ] Style: 디자인
- [ ] Fix: 버그 수정
- [ ] Test: 테스트 코드 작성

## 설명

### 이슈 번호

> https://github.com/codeit-fe2-2/taskify/issues/10
> https://github.com/codeit-fe2-2/taskify/issues/12

### 주요 변경 사항
Chip 컴포넌트 생성
Modal/button 생성

### 어떻게 동작하는지

<img width="571" alt="Screenshot 2024-01-27 at 9 02 11 PM" src="https://github.com/codeit-fe2-2/taskify/assets/116065415/8e3015d6-4747-4020-9f89-0fc5a507c0f3">

### To Reviewers
질문:
Chip: 다 만든건 아니고 색깔 동그라미에 체크 이미지가 올라가는걸 제가 미리 클릭이벤트에 넣어야 하는지 ? 
Modal/button: 다른 버튼 컴포넌트를 재활용하기로 했는데 그럼 파일을 지워야 할까요?

2024-01-28 13:07 UTC, ckswnskfk reviewed
공통 컴포넌트 구현하시느라 고생 많으셨습니다! 👍 
모든 chip을 버튼으로 구현하신 이유가 궁금하네요~!

2024-01-28 13:07 UTC, ckswnskfk commented on src/components/ui/Modal/Chips.tsx
> +}){
칩 컴포넌트인지 버튼 컴포넌트인지 네이밍이 좀 헷깔리네요 😢
제 생각엔 어떤 기능이 필요하다면 Button 컴포넌트 안에 Chip이 들어가는 식으로 구현돼야 할 것 같아요. 지금 컴포넌트는 onClick 등의 props도 없어서 어떻게 기능하는지 잘 모르겠습니다ㅠㅠ
다른 아이콘이 필요하면 어떻게 처리하면 좋을까요?

2024-01-28 13:07 UTC, ckswnskfk commented on src/components/ui/Modal/Chips.tsx
> +     <br/>
이 br 태그의 역할은 뭔가요? 스타일로 해결이 안될까요?

2024-01-28 13:07 UTC, ckswnskfk commented on src/components/ui/Modal/Chips.tsx
> +        </button>
이 부분은 컴포넌트로 활용할 수는 없을까요?

2024-01-28 13:07 UTC, ckswnskfk commented on tailwind.config.ts
> +      sortTextBgBlue: '#DBE6F7',
네이밍을 좀 더 일반화 시킬 수 있을까요?

2024-01-29 03:01 UTC, 00TaciTa00 requested changes

2024-01-29 03:01 UTC, 00TaciTa00 commented on src/components/ui/Modal/Chips.tsx
> +export function ColorDots({src,tagName, width, height}: {
<button className='size-9 rounded-full bg-violet2' />
이런 식으로 rounded-full를 사용해보는 건 어떨까요? 이러면 Props로 받아오는 것도 편할거에요!

2024-01-30 05:20 UTC, closed without merging