Feat: MyPage구현
codeit-fe2-2/taskify pull request #74
Opened 2024-02-07 15:24 UTC by BBoBBoM

프로필 수정 및 비밀번호 변경기능 수정 변경 요청을 위한 hooks 생성
userType을 위한 user.ts 수정 next.config파일 수정 :

## 어떤 변경인지

- [x] Feat: 기능 변경, 기능 추가
- [ ] Docs: 문서 작업
- [ ] Refactor: 기능 변경 없이 코드 수정
- [x] Style: 디자인
- [ ] Fix: 버그 수정
- [ ] Test: 테스트 코드 작성

## 설명
1. mypage  돌아가기 버튼, 프로필변경, 비밀번호변경, toast메시지창으로 구성되어 있습니다.
2. 프로필변경 기본 정보가 필요해 useGetMe로 정보를 가져왔습니다.
3. 프로필 변경 이미지 부분 미리보기 filereader가 있는데 그걸로 변환하니 속도도 느려지는 문제, 변환한 파일 이름이 너무 길어 그또한 문제가 될거 같아 프로필 변경으로 이미지를 선택하면 그 즉시 post요청으로 새로운 url을 반환 받아 화면에 보여주는 방식으로 구현을 했습니다. 
4. 이렇게 받아온 파일 형식 'sprint-fe-project.s3.ap-northeast-2.amazonaws.com ~~나머지'인데 이부분은 보안상 문제로 외부에서 이미지를 불러올때 막아놓은 부분때문에 next.config domains를 추가 했습니다.
5. 패스워드는 특별한 기능은없고 기존의 비밀번호 새비밀번호, 확인 절차를 거쳐 성공 실패로 나뉘는데 
6. 현재(기존) 비밀번호는 유저 정보등에 비밀번호가 딸려오지 않아 직접 요청을 하여 기존비밀번호가 맞지않으면 반환되는 것으로 모달을 보여주는 방식으로 구현을 했습니다. 
7. get Post Put 요청을 위해 hooks에 mypage폴더에 만들었는데 여기다 만드는것이 맞나요?
8. useAsync에 대한 이해가 부족해 axiosinstance만 사용하여 post put를 구현하였습니다. 

### 이슈 번호

> https://github.com/codeit-fe2-2/taskify/issues/70

### 주요 변경 사항
mypage profileChange addImage, PasswordChange로 나누어 구현 
### 어떻게 동작하는지
![스크린샷 2024-02-07 235326](https://github.com/codeit-fe2-2/taskify/assets/131963909/926721e7-ec23-41cc-bb51-3b2bf741c39f)

작동 동영상 1분정도 됩니다 어떻게 동작하는지 잠깐 시연해봤어요 
http://naver.me/5yBUREvX
### To Reviewers
로그인 토큰이 없으면 /페이지 보이고 토큰 동작하면 /dashboard/{첫번째 dashboardid} 로 이동하는데  /dashboard/{첫번째 dashboardid} 값은 어디서 받아와야하나요?

2024-02-08 02:29 UTC, 00TaciTa00 requested changes

2024-02-08 02:29 UTC, 00TaciTa00 commented on pages/mypage/index.tsx
> +				</div>
<img width="275" alt="image" src="https://github.com/codeit-fe2-2/taskify/assets/79896328/a4ca8723-884c-4ac6-beb0-37bf36ccc672"><br>
toastMessage 일부러 초록색으로 하신건가요?

2024-02-08 02:29 UTC, 00TaciTa00 commented on pages/mypage/index.tsx
> +				<div className='p-5 sm:p-3'>
<img width="942" alt="image" src="https://github.com/codeit-fe2-2/taskify/assets/79896328/2a7a3bae-6bef-49d4-94b0-bae8ee1d6efe">
<br>
번거로우시겠지만 여기에도 배경색 지정하셔야 할 거 같아요.

2024-02-08 02:32 UTC, BBoBBoM commented on pages/mypage/index.tsx
> +				</div>
얘는 없는사항이라 일단 막 구현해봤습니다 토스트 해보고 싶어서요... ㅋ 다른의견 있으시면 말씀해주세요!!

2024-02-08 02:33 UTC, BBoBBoM commented on pages/mypage/index.tsx
> +				<div className='p-5 sm:p-3'>
아그거 pr에 못남겼는데 화면이 저게 끝이더라구요

2024-02-09 11:25 UTC, 00TaciTa00 commented on pages/mypage/index.tsx
> +				</div>
ㅋㅋㅋ 아무래도 초록?색은 좀 그렇죠 ㅋㅋㅋ 마침 이 프로젝트에 대표 컬러가 있으니까 violet2와 white가 나을 거 같아요

2024-02-09 13:59 UTC, 00TaciTa00 approved these changes
해결했다 싶으시면 머지하세용

2024-02-09 18:48 UTC, ckswnskfk reviewed
몇 가지 디테일 빼고는 전반적으로 잘 동작하네요! 👍

데이터 페칭 함수를 use 로 시작하는 이름을 많이 지으셨던데, 커스텀 훅의 정의를 한 번 찾아보시면 좋을 것 같습니다.
dev에 올릴 땐 console 이나 미완성 컴포넌트는 올리지 않는게 좋을 것 같아요!

2024-02-09 18:48 UTC, ckswnskfk commented on pages/dashboard/[boardid]/index.tsx
> +		await useDeleteColumn(id);
useDeleteColumn는 훅이 아니라 use~ 로 시작하는 이름을 가지면 안될 것 같습니다.

2024-02-09 18:48 UTC, ckswnskfk commented on pages/dashboard/[boardid]/index.tsx
> +		await usePostDashboard(inputValue, dashboardId);
usePostDashboard도 훅이 아니네요

2024-02-09 18:48 UTC, ckswnskfk commented on pages/dashboard/[boardid]/index.tsx
> +		await usePutColumnName(inputValue, id);
usePutColumnName도 훅이 아니네요.

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/dashboard/CardList.tsx
> +			const result = await useGetCardList(2, column.id, page);
useGetCardList 는 훅이 아니네요

2024-02-09 18:48 UTC, ckswnskfk commented on src/types/card.ts
> +	card: Card;
card: Card[] 가 되어야 할 것 같네요

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/dashboard/CardList.tsx
> +				}));
이 부분 동작이 이상한 것 같습니다.
데이터는 column의 카드들을 불러오는데 그걸 매 번 추가하니 계속 쌓이기만 합니다.
<img width="1453" alt="image" src="https://github.com/codeit-fe2-2/taskify/assets/44164404/4332554f-727c-4328-8f31-36eee1059d90">
네트워크에서 불러온 카드 갯수는 하나지만 세개가 나오고 있습니다.

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/dashboard/CardList.tsx
> +			{isLoading && <div>Loading...</div>}
로딩 상태도 쓰셨군요! 👍

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/mypage/AddImage.tsx
> +			const imageUrl = await usePostProfileImageURL(file);
usePostProfileImageURL 도 훅이 아니네요ㅠㅠ

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/mypage/AddImage.tsx
> +				/>
여긴 로딩 이미지를 쓰셨는데 단순히 글씨로만 처리 된 곳도 있네요!

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/mypage/AddImage.tsx
> +				style={{ display: 'none' }}
tailwind 로 처리할 수 없나요?

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/mypage/PasswordChange.tsx
> +						/>
공통 Input 컴포넌트를 쓰시지 않은 이유가 있을까요?
그리고 htmlFor와 id가 셋 중 하나도 맞지 않네요...ㅋㅋㅋㅋㅋ

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/mypage/PasswordChange.tsx
> +						>
onClick 이 없어서 오류가 나고 있습니다

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/mypage/ProfileChange.tsx
> +			await usePutChangedUserInfo(nickname, imageUrl);
usePutChangedUserInfo도 훅이 아니군요!

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/mypage/ProfileChange.tsx
> +						/>
여기도 공통 Input 컴포넌트를 쓸 수 있으면 쓰면 좋겠네요. 그리고 여기도 htmlFor가 맞지 않는군요..ㅋㅋㅋ

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/ui/Card.tsx
dashboard 에도 Card가 있는데 여기도 있네요..?

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/ui/Modal/CardDetails.tsx
> +const CardDetails: React.FC<CardDetailsProps> = ({ cardId }) => {
React.FC가 군데군데 섞여있네요

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/ui/Modal/CardDetails.tsx
아마 카드를 클릭했을 때 모달로 상세 내용이 나오는 기능을 위해 컴포넌트를 만드신 걸로 보입니다.
이 경우 새로 데이터를 fetching할 필요 없이 그냥 Card에서 넘겨 받으면 될 것 같습니다.

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/ui/Modal/CardDetails.tsx
> +import { useGetCardDetail } from '@/src/hooks/Card/useGetCardList';
해당 함수가 없네요

2024-02-09 18:48 UTC, ckswnskfk commented on src/components/ui/Modal/CreateModal.tsx
여기도 Input 공통 컴포넌트를 사용하면 좋을 것 같고, htmlFor 또한 맞지 않네요.
그리고 86라인 input에 있는 h-10.5 는 아쉽게도 동작하지 않는군요

2024-02-09 22:43 UTC, BBoBBoM commented on pages/mypage/index.tsx
> +				</div>
확인 다음 pr에 반영할게요~

2024-02-09 22:44 UTC, BBoBBoM commented on pages/dashboard/[boardid]/index.tsx
> +const DashboardPage: React.FC<DashboardPageProps> = () => {
앗 저게 바꿔야지 했는데 못지우고 했네요 수정해놓도록 하겠습니다

2024-02-09 22:45 UTC, BBoBBoM commented on pages/dashboard/[boardid]/index.tsx
> +	console.log(columnList);
넵...... 죄송합니다

2024-02-10 09:40 UTC, merged